baseURL = "http://purod1st.github.io/"
languageCode = "en-us"
theme = "poison"
paginate = 10
pluralizelisttitles = false


[params]
    brand = "Purod1st"                      # name of your site - appears in the sidebar
    brand_image = "/images/Logo.png"    # path to the image shown in the sidebar
    description = "ИТ-специалист. Личный блог и портфолио." # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    favicon = "/images/Logo.png"             # path to favicon (defaults to favicon.png)

    # MENU PLACEHOLDER
    # Menu dict keys:
        # Name:         The name to display on the menu.
        # URL:          The directory relative to the content directory.
        # HasChildren:  If the directory's files should be listed.  Default is true.
        # Limit:        If the files should be listed, how many should be shown.
    menu = [
        {Name = "Обо мне", URL = "/about/", HasChildren = false},
        {Name = "Посты", URL = "/posts/", Pre = "Назад", HasChildren = true, Limit = 5},
	{Name = "Проекты", URL = "/projects/", Pre = "Назад", HasChildren = true, Limit = 5},

    ]

    discord_url = "https://discord.com"
    email_url = "mailto://user@domain"
    github_url = "https://github.com"
    gitlab_url = "https://gitlab.com"
    youtube_url = "https://youtube.com"


    # Hex colors for your sidebar.
    moon_sun_background_color = "#515151"   # default is #515151
    moon_sun_color = "#FFF"                 # default is #FFF
    sidebar_a_color = "#FFF"                # Цвет шрифта
    sidebar_bg_color = "#023B37"            # Задний фон
    sidebar_h1_color = "#FFF"               # Имя сайта
    sidebar_img_border_color = "#1B736B"    # рамка вокруг аватарки
    sidebar_p_color = "#A4D1BA"             # Цвет дополнит. шрифта
    sidebar_socials_color = "#A4D1BA"          # Цвет иконок соц сетей

    # Hex colors for your content in light mode.
    code_color = "#000"                     # default is #000
    code_background_color = "#E5E5E5"       # default is #E5E5E5
    code_block_color = "#FFF"               # Шрифт в блоке кода
    code_block_background_color = "#1B736B" # Цвет блока кода
    content_bg_color = "#FAF9F6"            # default is #FAF9F6
    date_color = "#09514C"                  # default is #515151
    link_color = "#095"                  # Цвет ссылок 
    list_color = "#000"                  # Шриф в списках
    post_title_color = "#303030"            # Цвет заголока поста
    table_border_color = "#E5E5E5"          # Цвет рамки таблиц
    table_stripe_color = "#F9F9F9"          # Цвет чётных ячеек таблиц
    text_color = "#09514C"                     # Цвет текста

    # Hex colors for your content in dark mode
    code_color_dark = "#FFF"                        # default is #FFF
    code_background_color_dark = "#515151"          # default is #515151
    code_block_color_dark = "#FFF"                  # default is #FFF
    code_block_background_color_dark = "#1B736B"    # default is #272822
    content_bg_color_dark = "#012F2B"               # default is #121212
    date_color_dark = "#A4D1BA"                     # default is #9A9A9A
    link_color_dark = "#095"                     # default is #268BD2
    list_color_dark = "#FFF"                     # default is #9D9D9D
    post_title_color_dark = "#FFF"               # default is #DBE2E9
    table_border_color_dark = "#1B736B"             # default is #515151
    table_stripe_color_dark = "#09514C"             # default is #202020
    text_color_dark = "#A4D1BA"                        # default is #EEE


[taxonomies]
    series = 'series'
    tags = 'tags'
